endpoints:
    health:
        sensitive: false
    restart:
        enabled: true
    shutdown:
        enabled: true
info:
    component: Zuul Server
zuul:
    routes:
        filters:
            path: /filter
            service-id: aviation-settings
        getFilters:
            path: /getFilters
            service-id: aviation-settings
        getSplashDate:
            path: /getSplashDate
            service-id: aviation-settings
        loadComponent:
            path: /loadComponent
            service-id: aviation-settings
        navigationToRemoval:
            path: /navigationToRemoval
            service-id: aviation-settings
        navigationToRemoval-ui:
            path: /navigationToRemoval-ui
            service-id: aviation-component-ui
        oldaviation:
            path: /aviation-ui/**
            service-id: aviation-ui
        paginationStatus:
            path: /paginationStatus
            service-id: aviation-component-ui
        postComponentIds:
            path: /postComponentIds
            service-id: aviation-component-ui
        removalReport:
            path: /removalReport
            service-id: aviation-component-ui
        settings:
            path: /aviation-settings/**
            service-id: aviation-settings
        settingsjs:
            path: /js/settings.js
            service-id: aviation-settings
        splash:
            path: /splash
            service-id: aviation-settings
        splashScreen:
            path: /splashScreen
            service-id: aviation-settings
        test:
            path: /test
            service-id: aviation-component-ui
        testhtml:
            path: /test.html
            service-id: aviation-component-ui
        testjs:
            path: /js/test.js
            service-id: aviation-component-ui
        triangle:
            path: /img/triangle.png
            service-id: aviation-component-ui
        unitfiltercss:
            path: /css/unitFilter.css
            service-id: aviation-settings
        unitjs:
            path: /js/unit.js
            service-id: aviation-settings
        utilityjs:
            path: /js/Utility.js
            service-id: aviation-settings
        saveFilter:
            path: /saveFilter
            service-id: aviation-settings
        updateFilter:
            path: /updateFilter
            service-id: aviation-settings
---
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
---
server:
  context-path: /
---
spring:
  profiles: local
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  profiles: local, cloud
  datasource:
    url: ${cloud.services.postgres-sql.connection.jdbcUrl:jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root}
---
 eureka:
  instance:
    non-secure-port-enabled: false
    secure-port-enabled: true
    hostname: ${vcap.application.uris[0]:localhost:8761}
    status-page-url: https://${eureka.instance.hostname}/info
    health-check-url: https://${eureka.instance.hostname}/health
    home-page-url: https://${eureka.instance.hostname}/
    secure-virtual-host-name: https://${vcap.application.uris[0]:localhost:8761}
  
  client:
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:http://localhost:8761/eureka/}          
      
---
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

---
 spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.PostgreSQLDialect 
  http:
    multipart:
      max-request-size: 10Mb